sudo: required
services:
  - docker
script: 
  - docker build -t test-jira-app .    
  - docker ps 
  - docker images ls
deploy:
 provider: heroku
 script:
  - heroku container:push test-jira-app --app quiet-beach-04344
 api-key: $HEROKU_API_KEY
 app: test-jira-app
