sudo: required
services:
  - docker
script: 
  - docker build -t test-jira-app .    
  - docker ps 
  - docker images ls
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USERNAME" --password-stdin registry.heroku.com
#   - docker login --username=$REGISTRY_USER --password=$REGISTRY_PASS registry.heroku.com
  - heroku container:push test-jira-app --app quiet-beach-04344
deploy:
 provider: heroku
 script:
  - heroku container:push test-jira-app --app quiet-beach-04344
 api-key: $HEROKU_API_KEY
 app: test-jira-app
