sudo: required
services:
  - docker
script: 
  - docker build -t post .
  - heroku container:login
  - heroku container:push post --app quiet-beach-04344
deploy:
  provider: script
  script: 
    - docker build -t post .
    - heroku container:login
    - heroku container:push post --app quiet-beach-04344
  on:
    branch: master
