sudo: required
services:
  - docker
script: 
  - docker build -t post
  - heroku container:login
  - heroku container:push post
deploy:
  provider: script
  script: 
    - docker build -t post
    - heroku container:login
    - heroku container:push post
  on:
    branch: master
